spring:
  application:
    name: skill-trade

  datasource:
    url: jdbc:mysql://localhost:3306/skill-trade
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: 7IK87Kmc7IK8IOuwseyXlOuTnCDsl5Tsp4Dri4jslrQg7LGE7JqpIOqzvOygnCBKV1Qg67mE67CAIO2CpA==
  access-token-validate-in-seconds: 3600
  refresh-token-validate-in-seconds: 86400
