spring:
  application:
    name: skill-trade

  datasource:
    url: jdbc:mysql://localhost:3306/skill-trade
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop

security:
  grant-type: Bearer
  jwt:
    secret: 7IK87Kmc7IK8IOuwseyXlOuTnCDsl5Tsp4Dri4jslrQg7LGE7JqpIOqzvOygnCBKV1Qg67mE67CAIO2CpA==
    access-token-validate-in-seconds: 3600
    refresh-token-validate-in-seconds: 86400

oauth:
  oidc:
    google:
      login-url: https://accounts.google.com/o/oauth2/v2/auth}
      token-request-url: https://oauth2.googleapis.com/token
      grant-type: authorization_code
      client-id: {}
      redirect-uri: {}
      client-secret : {}
